# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "looker.nodeLabels" . | nindent 4 }}
  name: looker-clustered-api-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: looker-api
    port: 443
    protocol: TCP
    targetPort: looker-api
  selector:
    {{- include "looker.nodeSelectorLabels" . | nindent 4 }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "looker.nodeLabels" . | nindent 4 }}
  name: looker-clustered-web-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: looker-web
    port: 443
    protocol: TCP
    targetPort: looker-web
  selector:
    {{- include "looker.nodeSelectorLabels" . | nindent 4 }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "looker.nodeLabels" . | nindent 4 }}
  name: looker-prom-jmx-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: jmx-metrics
    port: 80
    protocol: TCP
    targetPort: jmx-metrics
  selector:
    {{- include "looker.selectorLabels" . | nindent 4 }}
  type: ClusterIP